"""
BaseUniv3WethCbbtcYield Strategy Package.

Generated by: almanak strat new
"""

try:
    from .strategy import BaseUniv3WethCbbtcYieldStrategy
except ImportError:
    from strategy import BaseUniv3WethCbbtcYieldStrategy

__all__ = [
    "BaseUniv3WethCbbtcYieldStrategy",
]
